#!/bin/bash

P3=
if [[ -f $(which python3.7) ]]; then
    P3=3.7
else
    echo "WARNING: Could not find python 3.7 in path. You probable want to 'sudo apt install python3.6-venv'."
fi

CMD=$1
shift

if [ $CMD = "install" ]; then
    python${P3} -m venv venv
    . ./venv/bin/activate || exit -1
    pip install --upgrade pip || echo "Please first sudo apt install python${P3}-pip"
    pip install --upgrade setuptools
    pip install --upgrade -r requirements.txt
    exit 0
fi

if [ ! -f "venv/bin/activate" ]; then
    ./rush install
fi

. ./venv/bin/activate || exit -1

if [ $CMD = "server" ]; then
    flask run --host=0.0.0.0 --port=5000 "$@"
elif [ $CMD = "dcf" ]; then
    python dcf.py "$@"
elif [ $CMD = "lint" ]; then
    mypy *.py &&
        flake8 &&
        (yapf -d *.py >/dev/null || (echo 'Format not happy, do ./py format!' && exit -1))
elif [ $CMD = "format" ]; then
    yapf -i *.py "$@"
elif [ $CMD = "test" ]; then
    ./py lint && python -m pytest -v -q python/ "$@"
else
    "$CMD" "$@"
fi
